---
apiVersion: v1
kind: Service
metadata:
    name: predixy
    labels:
        role: predixy
spec:
    selector:
        role: predixy
    ports:
        - port: 7617
          targetPort: 7617
          name: predixy
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: predixy-conf
data:
    predixy.conf: |+
        WorkerThreads 8
        ClientTimeout 300
        LogVerbSample 0
        LogDebugSample 0
        LogInfoSample 0
        LogNoticeSample 0
        LogWarnSample 0
        LogErrorSample 0
        Include cluster.conf
    cluster.conf: |+
        ClusterServerPool {
            RefreshInterval 1 # poll cluster info per second
            ServerTimeout 1
            ServerFailureLimit 10
            ServerRetryTimeout 1
            KeepAlive 120
            Servers {
                + redis-cluster-0.redis-cluster.default.svc.cluster.local:6379
                + redis-cluster-1.redis-cluster.default.svc.cluster.local:6379
                + redis-cluster-2.redis-cluster.default.svc.cluster.local:6379
            }
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: predixy
    labels:
        role: predixy
spec:
    replicas: 1
    selector:
        matchLabels:
            role: predixy
    template:
        metadata:
            labels:
                role: predixy
        spec:
            containers:
                - name: predixy
                  image: terryalu/predixy
                  ports:
                      - containerPort: 7617
                  volumeMounts:
                      - name: conf
                        mountPath: /conf
                        readOnly: false
                  command: ["sh", "-c"]
                  args:
                      - cp /conf/predixy.conf /etc/conf/predixy.conf &&
                        cp /conf/cluster.conf /etc/conf/cluster.conf &&
                        predixy /etc/conf/predixy.conf
                  resources:
                      limits:
                          cpu: 3
            volumes:
                - name: conf
                  configMap:
                      name: predixy-conf
                      defaultMode: 0777
