---
apiVersion: v1
kind: Service
metadata:
    name: twemproxy
    labels:
        role: twemproxy
spec:
    selector:
        role: twemproxy
    ports:
        - port: 7777
          targetPort: 7777
          name: twemproxy
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: twemproxy-conf
data:
    proxy.conf: |+
        pool:
          listen: 0.0.0.0:7777
          hash: fnv1a_64
          distribution: ketama
          auto_eject_hosts: false
          timeout: 400
          redis: true
          preconnect: true
          server_connections: 1
          servers:
              - redis-cluster-0.redis-cluster.default.svc.cluster.local:6379:1
              - redis-cluster-1.redis-cluster.default.svc.cluster.local:6379:1
              - redis-cluster-2.redis-cluster.default.svc.cluster.local:6379:1
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: twemproxy
    labels:
        role: twemproxy
spec:
    replicas: 8
    selector:
        matchLabels:
            role: twemproxy
    template:
        metadata:
            labels:
                role: twemproxy
        spec:
            containers:
                - name: twemproxy
                  image: terryalu/twemproxy
                  ports:
                      - containerPort: 7777
                  env:
                      - name: CONFPATH
                        value: "/conf"
                  volumeMounts:
                      - name: conf
                        mountPath: /conf
                        readOnly: false
                  command: ["nutcracker", "-c", "/conf/proxy.conf"]
                  #resources:
                      #limits:
                          #cpu: 313m
            volumes:
                - name: conf
                  configMap:
                      name: twemproxy-conf
                      defaultMode: 0777
